dashboard_vehicule/backend/urls.py
from django.urls import path
from . import views

app_name = 'backend'

urlpatterns = [
    path('', views.index, name='index'),  
]

dashboard_vehicule/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.data_view, name='data')
    ]

dashboard_vehicule/dashboard_vehicule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),  # Défini un chemin pour "backend"
    path('dashboard/', include('dashboard.urls'))
]

dashboard_vehicule/backend/models.py
from django.db import models

# Create your models here.

dashboard_vehicule/dashboard/models.py
from django.db import models

# Create your models here.

dashboard_vehicule/backend/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request,'backend/index.html')

dashboard_vehicule/dashboard/views.py
from django.shortcuts import render
from .models_legacy import RawEntretiens
from django.db.models import Sum
import plotly.express as px
from django.utils.safestring import mark_safe

def data_view(request):
    """
    Vue de mes données de la table PostgreSQL via models_legacy.py.
    Permet de filtrer les données selon l'immatriculation et le type d'opération.
    Affiche les immatriculations distinctes et les opérations distinctes.
    """
    # Récupération de toutes les données
    entretien_data = RawEntretiens.objects.all()

    # Filtrer selon l'immatriculation si un paramètre 'immat' est présent dans l'URL
    immat = request.GET.get('immat')
    if immat:
        entretien_data = entretien_data.filter(immat=immat)

    # Extraction des immatriculations distinctes
    distinct_immat = RawEntretiens.objects.values_list('immat', flat=True).distinct()

    # Filtrer selon le type d'operation
    operation = request.GET.get('operation')
    if operation:
        entretien_data = entretien_data.filter(operation=operation)
    
    # Opérations distinctes (tri avec None après le vide)
    distinct_operation = list(
        RawEntretiens.objects.values_list('operation', flat=True).distinct()
    )
    distinct_operation.sort(key=lambda x: (x is not None, x))

    # Calcul du montant total des coûts
    total_cost = entretien_data.aggregate(Sum('cost'))['cost__sum'] or 0
    # Format avec espace comme séparateur de milliers et deux chiffres après la virgule
    formatted_total_cost = f"{total_cost:,.2f}".replace(',', ' ').replace('.', ',')

    # Répartition des coûts par opération
    costs_by_operation = (
        entretien_data.values('operation')
        .annotate(total_cost=Sum('cost'))
        .order_by('-total_cost')
    )
    if not immat:
        # Si aucune immatriculation n'est sélectionnée, on prend les 5 premières opérations
        costs_by_operation = costs_by_operation[:5]

    operation_fig = px.pie(
        names=[item['operation'] for item in costs_by_operation],
        values=[item['total_cost'] for item in costs_by_operation],
        
    )
    operation_chart = mark_safe(operation_fig.to_html(full_html=False))

# barplot des coûts totaux par immatriculation

    # barplot des coûts totaux par immatriculation (top 8) avec axes inversés
    bar_fig = px.bar(
        x=[item['total_cost'] for item in entretien_data.values('immat').annotate(total_cost=Sum('cost')).order_by('-total_cost')[:8]],  # Axe X : coûts totaux
        y=[item['immat'] for item in entretien_data.values('immat').annotate(total_cost=Sum('cost')).order_by('-total_cost')[:8]],  # Axe Y : immatriculations
        orientation='h'  # Orientation horizontale
    )
    # Supprimer les titres des axes
    bar_fig.update_xaxes(title=None)  # Supprimer le titre de l'axe X
    bar_fig.update_yaxes(title=None)  # Supprimer le titre de l'axe Y


    bar_fig.update_yaxes(categoryorder='total ascending')


    operation_histogram = mark_safe(bar_fig.to_html(full_html=False))



    return render(request, 'dashboard/data.html', {
        'entretien_data': entretien_data,
        'distinct_immat': distinct_immat,  # Passer les immatriculations distinctes au template
        'distinct_operations': distinct_operation,  # Passer les opérations distinctes au template
        'total_cost': formatted_total_cost,  # Passer le coût total au template
        'operation_chart': operation_chart,  # Graphique des opérations
        'operation_histogram': operation_histogram,  # Graphique des opérations
    })

dashboard_vehicule/backend/templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <!-- tailwind css -->
    <link rel="stylesheet" href="{% static 'dist/styles.css' %}" />
    <!-- boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
  </head>

  <body class="bg-white">
    <div
      class="navbar shadow-sm shadow-accent justify-between items-center bg-neutral-100"
    >
      <div class="flex space-x-2 justify-start">
        <a href="" class="btn btn-outline btn-secondary text-lg">LOGIN</a>
        <a href="" class="btn btn-outline btn-secondary text-lg">SIGN UP</a>
      </div>
      <div class="flex-1 flex justify-center space-x-4">
        <a href="{% url 'backend:index' %}" class="btn btn-outline btn-info"
          >HOME</a
        >
        <a href="{% url 'dashboard:data' %}" class="btn btn-outline btn-info"
          >DASHBOARD</a
        >
      </div>

      <div class="flex justify-end space-x-2 ">
        <a
          class="text-3xl text-primary hover:text-accent cursor-pointer"
          href="https://www.linkedin.com/in/cedric-le-tutour"
          target="_blank"
          aria-label="LinkedIn"
          ><i class="bx bxl-linkedin"></i
        ></a>

        <a
          class="text-3xl text-primary hover:text-accent cursor-pointer"
          href="https://github.com/CedricLt44"
          target="_blank"
          aria-label="GitHub"
          ><i class="bx bxl-github"></i
        ></a>
        <a
          class=" bx bx-cog text-3xl text-primary hover:text-accent cursor-pointer"
          href="{% url 'admin:index' %}"
        ></a>
      </div>
    </div>
    <main class="m-9 py-8 px-8">{% block content %} {% endblock %}</main>
  </body>
</html>

dashboard_vehicule/backend/templates/backend/index.html
{% extends 'backend/base.html' %} {% load static %} {% block content %}
<header class="py-5 text-center">
  <h1 class="flex justify-center text-3xl">Bienvenue {{ user }} !</h1>
</header>
{% endblock content %}

dashboard_vehicule/dashboard/templates/dashboard/data.html
{% extends 'backend/base.html' %}
<!-- charge les templates -->
{% load static %}
<!-- debut de la page -->
{% block content %}
<main>
  <header class="flex justify-center">
    <h2 class="text-2xl mb-6">Coûts des entretiens de la flotte</h2>
  </header>

  <!-- Filtres -->
  <form method="get" class="mb-4">
    <div class="flex space-x-4 my-6"> <!-- Utilisation de flexbox pour aligner les éléments -->
      <!-- Sélectionner une immatriculation -->
      <div>
        <label class="label block mb-2">Sélectionner une immatriculation</label>
        <select name="immat" onchange="this.form.submit()" class="select select-bordered bg-base-100">
          <option value="">-- Toutes --</option>
          {% for i in distinct_immat %}
            <option value="{{ i }}" {% if request.GET.immat == i %}selected{% endif %}>{{ i }}</option>
          {% endfor %}
        </select>
      </div>
      <!-- Sélectionner un type d'opération -->
      <div>
        <label class="label block mb-2">Sélectionner un type d'opération</label>
        <select name="operation" onchange="this.form.submit()" class="select select-bordered bg-base-100">
          <option value="">-- Toutes --</option>
          {% for o in distinct_operations %}
            <option value="{{ o }}" {% if request.GET.operation == o %}selected{% endif %}>{{ o }}</option>
          {% endfor %}
        </select>
      </div>
      <!-- PieChart pour le montant total des coûts -->
      <div>
        <label class="label block mb-1">Montant total des coûts</label>      
        <div class="shadow-lg shadow-accent p-2">              
           <p class="text-2xl font-semibold">{{ total_cost }} €</p>         
        </div>
      </div>
    </div>
  </form>
  <!-- Tableaux -->
  <div
    class="h-96 overflow-x-auto rounded-box border border-neutral-content/5 bg-white"
  >
    <table class="table table-zebra">
      <!-- Head -->
      <thead class="bg-accent sticky top-0 z-10">
        <tr>
          <th>Date</th>
          <th>Immatriculation</th>
          <th>Coût</th>
          <th>operation</th>
          <th>Fournisseur</th>
        </tr>
      </thead>
      <!-- Body -->
      <tbody>
        {% for row in entretien_data %}
        <tr>
          <td>{{ row.date|date:"d/m/Y" }}</td>
          <td>{{ row.immat }}</td>
          <td>{{ row.cost|floatformat:2 }} €</td>
          <td>{{ row.operation }}</td>
          <td>{{ row.supplier }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Graphiques -->
  <div class="flex flex-wrap space-x-4 my-6">
    <!-- pieChart -->
    <div class="card w-[50rem] shadow-lg shadow-accent mt-6">
      <div class="card-body items-center">
        <h3 class="text-xl font-semibold mb-4">Répartition des coûts par opération</h3>
        <div>{{ operation_chart|safe }}</div>
      </div>
    </div>

    <!-- barChart -->
    <div class="card w-[50rem] shadow-lg shadow-accent mt-6">
      <div class="card-body items-center">
        <h3 class="text-xl font-semibold mb-4">Coûts totaux par immatriculation</h3>
        <div>{{ operation_histogram|safe }}</div>
      </div>
    </div>
  </div>

</main>
<!-- fin de la page -->
{%endblock %}